module.exports = {
  ADMIN_TYPE: 1000,
  VENDOR_TYPE: 2000,
  CUSTOMER_TYPE: 3000,
  EXPIRED: "expired",
  UNEXPIRED: "unexpired",
  ACTIVATE: 1,
  DEACTIVATE: 0,
  COUNTRY: "nigeria",
  WEB: "web",
  MOBILE: "mobile",
  MAP_STATION_TYPE: "Feature",
  GEOMETRY_TYPE: "Point",
  MEASURE_UNIT: "Kg",
};
