module.exports = {
  SUCCESSFUL: "successful",
  SUCCESS: "success",
  ENABLED: "enabled",
  ERROR: "error",
  FAILED: "failed",
  CANCELLED: "cancelled",
  EXPIRED: "expired",
  UNEXPIRED: "unexpired",
  ACTIVATED: "activated",
  ACTIVATE: "activate",
  DEACTIVATED: "deactivated",
  DEACTIVATE: "deactivate",
  PENDING: "pending",
  PROCESSING: "processing",
  COMPLETED: "completed",
  DECLINED: "declined",
  VENDOR_SATISFIED: "vendor-satisfied",
  CUSTOMER_SATISFIED: "customer-satisfied",
};
